spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://emysql:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 197600
  redis:
    host: eredis
    port: 6380
#    password: 197600
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 8
        min-idle: 0
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    username: niko
    password: 197600
    host: erabbit
    port: 5673
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: ees:9201
