spring:
  profiles:
    active: docker

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

file:
  upload:
    dir: ${user.dir}/upload
server:
  port:
